use anyhow::Result;
use serde::{Deserialize, Serialize};

use crate::tpls::engine::render_template;

const MICRO_PROVIDER_TPL: &str = r#"// Code generated by whale_fall. DO NOT EDIT.
package provider

var (
	{{#each micro_list}}
	{{this}} {{this}}Interface
	{{/each}}
)
"#;

#[derive(Debug, Serialize, Deserialize, Default)]
pub struct MicroProvider {
    pub micro_list: Vec<String>,
}

impl MicroProvider {
    pub fn execute(&self) -> Result<String> {
        render_template(MICRO_PROVIDER_TPL, self)
    }
}
